settings:
  docker:
    parent_image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  query_limit: 4
  batch_size: 10
  sparse_model_path: models/sparse_bm25_model.pkl